spring.application.name=springAI

server.port=8085
spring.ai.google.genai.api-key=${GCP_API_KEY}


logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=DEBUG

spring.datasource.url=jdbc:mysql://localhost:3306/spring_ai
spring.datasource.username=${GCP_API_KEY}
spring.datasource.password=${GCP_API_KEY}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.chat.memory.repository.jdbc.platform=mysql